#! /bin/bash

for src in json-packs/*/; do
	pack=${src%*/} # remove the trailing "/"
	pack=${pack##*/} # get everything after the final "/"
	fvtt package --id mythicbastionland --type System pack ${pack} -c --json --in "${src}" --out "packs"
done
